# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AbaeSharedGeoms
                                 A QGIS plugin
 Abae Shared Geoms
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-09-14
        copyright            : (C) 2022 by Eduardo Guillen
        email                : eguillen@abae.gob.ve
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AbaeSharedGeoms class from file AbaeSharedGeoms.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .AbaeSharedGeomsPlugin import AbaeSharedGeoms
    return AbaeSharedGeoms(iface)
